### ISSUE TITLE
Build Failure: DataWord(byte[]) has private access in DataWord

### ISSUE THREAD

**Issue by MysticRyuujin** [ether-camp/ethereum-harmony#118]
I've ran a `git pull` and cleared my cache `rm -rf /root/.gradle/caches/`

Now it refuses to build.

Out:
```
Download https://jcenter.bintray.com/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar
:runMain FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings
1 actionable task: 1 executed
:runMain
Set default heap size for task -Xmx1500m
Running Java with [-server, -Xss2M, -XX:+UseCompressedOops, -XX:+HeapDumpOnOutOfMemoryError, -XX:-OmitStackTraceInFastThrow, -Ddatabase.dir=/root/ethereumj/database, -Dsync.fast.enabled=true, -Dsync.fast.skipHistory=true, -Dethereumj.conf.res=ethereumj.conf, -Ddatabase.name=database, -DnetworkProfile=main, -Xmx1500m]
:runMain FAILED
```

Error:
```
/root/ethereum-harmony/src/main/java/com/ethercamp/harmony/jsonrpc/EthJsonRpcImpl.java:474: error: DataWord(byte[]) has private access in DataWord
                getStorageValue(addressAsByteArray, new DataWord(hexToByteArray(storageIdx)));
                                                    ^
/root/ethereum-harmony/src/main/java/com/ethercamp/harmony/jsonrpc/EthJsonRpcImpl.java:1045: error: DataWord(byte[]) has private access in DataWord
                    logFilter.withTopic(new DataWord(hexToByteArray((String) topic)).getData());
                                        ^
/root/ethereum-harmony/src/main/java/com/ethercamp/harmony/jsonrpc/EthJsonRpcImpl.java:1049: error: DataWord(byte[]) has private access in DataWord
                        t.add(new DataWord(hexToByteArray(s)).getData());
                              ^
Note: /root/ethereum-harmony/src/main/java/com/ethercamp/harmony/service/WalletService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

FAILURE: Build failed with an exception.

* Where:
Build file '/root/ethereum-harmony/build.gradle' line: 335

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30
```

**Comment by zilm13** [comment]
@MysticRyuujin working on it, will take some time
I'll ping you back when the fix is available

**Comment by MysticRyuujin** [comment]
Well, now I'm getting these:

```
Server started at http://localhost:8080
18:05:47.113 ERROR [c.e.c.s.d.StorageDictionaryVmHook]  Error within handler: 
java.util.ConcurrentModificationException: null
        at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1648)
        at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at com.ethercamp.contrdata.storage.dictionary.Sha3Index.contains(Sha3Index.java:79)
        at com.ethercamp.contrdata.storage.dictionary.Sha3Index.add(Sha3Index.java:85)
        at com.ethercamp.contrdata.storage.dictionary.StorageDictionaryVmHook.step(StorageDictionaryVmHook.java:69)
        at org.ethereum.vm.VM.lambda$step$0(VM.java:391)
        at org.ethereum.vm.VM.callVmHookAction(VM.java:1406)
        at org.ethereum.vm.VM.step(VM.java:391)
        at org.ethereum.vm.VM.play(VM.java:1366)
        at org.ethereum.core.TransactionExecutor.go(TransactionExecutor.java:312)
        at org.ethereum.core.BlockchainImpl.applyBlock(BlockchainImpl.java:884)
        at org.ethereum.core.BlockchainImpl.processBlock(BlockchainImpl.java:854)
        at org.ethereum.core.BlockchainImpl.addImpl(BlockchainImpl.java:580)
        at org.ethereum.core.BlockchainImpl.add(BlockchainImpl.java:530)
        at org.ethereum.core.BlockchainImpl.tryToConnect(BlockchainImpl.java:437)
        at org.ethereum.sync.SyncManager.produceQueue(SyncManager.java:289)
        at java.lang.Thread.run(Thread.java:748)
18:05:47.149 ERROR [c.e.c.s.d.StorageDictionaryVmHook]  Error within handler: 
java.util.ConcurrentModificationException: null
        at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1648)
        at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at com.ethercamp.contrdata.storage.dictionary.Sha3Index.contains(Sha3Index.java:79)
        at com.ethercamp.contrdata.storage.dictionary.Sha3Index.add(Sha3Index.java:85)
        at com.ethercamp.contrdata.storage.dictionary.StorageDictionaryVmHook.step(StorageDictionaryVmHook.java:69)
        at org.ethereum.vm.VM.lambda$step$0(VM.java:391)
        at org.ethereum.vm.VM.callVmHookAction(VM.java:1406)
        at org.ethereum.vm.VM.step(VM.java:391)
        at org.ethereum.vm.VM.play(VM.java:1366)
        at org.ethereum.core.TransactionExecutor.go(TransactionExecutor.java:312)
        at org.ethereum.core.PendingStateImpl.executeTx(PendingStateImpl.java:419)
        at org.ethereum.core.PendingStateImpl.addPendingTransactionImpl(PendingStateImpl.java:226)
        at org.ethereum.core.PendingStateImpl.addPendingTransactions(PendingStateImpl.java:166)
        at org.ethereum.net.eth.handler.Eth62.processTransactions(Eth62.java:406)
        at org.ethereum.net.eth.handler.Eth62.channelRead0(Eth62.java:153)
        at org.ethereum.net.eth.handler.Eth63.channelRead0(Eth63.java:83)
        at org.ethereum.net.eth.handler.Eth63.channelRead0(Eth63.java:56)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
        at org.ethereum.net.rlpx.NettyByteToMessageCodec.channelRead(NettyByteToMessageCodec.java:73)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at org.ethereum.net.server.WireTrafficStats$TrafficStatHandler.channelRead(WireTrafficStats.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:748)
18:05:47.659 ERROR [c.e.c.s.d.StorageDictionaryVmHook]  Error within handler: 
java.util.ConcurrentModificationException: null
        at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1648)
        at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at com.ethercamp.contrdata.storage.dictionary.Sha3Index.contains(Sha3Index.java:79)
        at com.ethercamp.contrdata.storage.dictionary.Sha3Index.add(Sha3Index.java:85)
        at com.ethercamp.contrdata.storage.dictionary.StorageDictionaryVmHook.step(StorageDictionaryVmHook.java:69)
        at org.ethereum.vm.VM.lambda$step$0(VM.java:391)
        at org.ethereum.vm.VM.callVmHookAction(VM.java:1406)
        at org.ethereum.vm.VM.step(VM.java:391)
        at org.ethereum.vm.VM.play(VM.java:1366)
        at org.ethereum.core.TransactionExecutor.go(TransactionExecutor.java:312)
        at org.ethereum.core.PendingStateImpl.executeTx(PendingStateImpl.java:419)
        at org.ethereum.core.PendingStateImpl.updateState(PendingStateImpl.java:398)
        at org.ethereum.core.PendingStateImpl.processBest(PendingStateImpl.java:323)
        at org.ethereum.core.BlockchainImpl.lambda$tryToConnect$0(BlockchainImpl.java:462)
        at org.ethereum.core.EventDispatchThread.lambda$invokeLater$1(EventDispatchThread.java:78)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
18:05:47.667 ERROR [c.e.c.s.d.StorageDictionaryVmHook]  Error within handler: 
java.util.ConcurrentModificationException: null
        at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1648)
        at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at com.ethercamp.contrdata.storage.dictionary.Sha3Index.contains(Sha3Index.java:79)
        at com.ethercamp.contrdata.storage.dictionary.Sha3Index.add(Sha3Index.java:85)
        at com.ethercamp.contrdata.storage.dictionary.StorageDictionaryVmHook.step(StorageDictionaryVmHook.java:69)
        at org.ethereum.vm.VM.lambda$step$0(VM.java:391)
        at org.ethereum.vm.VM.callVmHookAction(VM.java:1406)
        at org.ethereum.vm.VM.step(VM.java:391)
        at org.ethereum.vm.VM.play(VM.java:1366)
        at org.ethereum.core.TransactionExecutor.go(TransactionExecutor.java:312)
        at org.ethereum.core.PendingStateImpl.executeTx(PendingStateImpl.java:419)
        at org.ethereum.core.PendingStateImpl.updateState(PendingStateImpl.java:398)
        at org.ethereum.core.PendingStateImpl.processBest(PendingStateImpl.java:323)
        at org.ethereum.core.BlockchainImpl.lambda$tryToConnect$0(BlockchainImpl.java:462)
        at org.ethereum.core.EventDispatchThread.lambda$invokeLater$1(EventDispatchThread.java:78)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
18:05:48.543 ERROR [c.e.c.s.d.StorageDictionaryVmHook]  Error within handler: 
java.util.ConcurrentModificationException: null
        at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1648)
        at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at com.ethercamp.contrdata.storage.dictionary.Sha3Index.contains(Sha3Index.java:79)
        at com.ethercamp.contrdata.storage.dictionary.Sha3Index.add(Sha3Index.java:85)
        at com.ethercamp.contrdata.storage.dictionary.StorageDictionaryVmHook.step(StorageDictionaryVmHook.java:69)
        at org.ethereum.vm.VM.lambda$step$0(VM.java:391)
        at org.ethereum.vm.VM.callVmHookAction(VM.java:1406)
        at org.ethereum.vm.VM.step(VM.java:391)
        at org.ethereum.vm.VM.play(VM.java:1366)
        at org.ethereum.core.TransactionExecutor.go(TransactionExecutor.java:312)
        at org.ethereum.core.BlockchainImpl.applyBlock(BlockchainImpl.java:884)
        at org.ethereum.core.BlockchainImpl.processBlock(BlockchainImpl.java:854)
        at org.ethereum.core.BlockchainImpl.addImpl(BlockchainImpl.java:580)
        at org.ethereum.core.BlockchainImpl.add(BlockchainImpl.java:530)
        at org.ethereum.core.BlockchainImpl.tryConnectAndFork(BlockchainImpl.java:376)
        at org.ethereum.core.BlockchainImpl.tryToConnect(BlockchainImpl.java:446)
        at org.ethereum.sync.SyncManager.produceQueue(SyncManager.java:289)
        at java.lang.Thread.run(Thread.java:748)
18:05:52.219 ERROR [c.e.c.s.d.StorageDictionaryVmHook]  Error within handler: 
java.util.ConcurrentModificationException: null
        at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1648)
        at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at com.ethercamp.contrdata.storage.dictionary.Sha3Index.contains(Sha3Index.java:79)
        at com.ethercamp.contrdata.storage.dictionary.Sha3Index.add(Sha3Index.java:85)
        at com.ethercamp.contrdata.storage.dictionary.StorageDictionaryVmHook.step(StorageDictionaryVmHook.java:69)
        at org.ethereum.vm.VM.lambda$step$0(VM.java:391)
        at org.ethereum.vm.VM.callVmHookAction(VM.java:1406)
        at org.ethereum.vm.VM.step(VM.java:391)
        at org.ethereum.vm.VM.play(VM.java:1366)
        at org.ethereum.core.TransactionExecutor.go(TransactionExecutor.java:312)
        at org.ethereum.core.BlockchainImpl.applyBlock(BlockchainImpl.java:884)
        at org.ethereum.core.BlockchainImpl.processBlock(BlockchainImpl.java:854)
        at org.ethereum.core.BlockchainImpl.addImpl(BlockchainImpl.java:580)
        at org.ethereum.core.BlockchainImpl.add(BlockchainImpl.java:530)
        at org.ethereum.core.BlockchainImpl.tryToConnect(BlockchainImpl.java:437)
        at org.ethereum.sync.SyncManager.produceQueue(SyncManager.java:289)
        at java.lang.Thread.run(Thread.java:748)
18:05:52.249 ERROR [c.e.c.s.d.StorageDictionaryVmHook]  Error within handler: 
java.util.ConcurrentModificationException: null
        at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1648)
        at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at com.ethercamp.contrdata.storage.dictionary.Sha3Index.contains(Sha3Index.java:79)
        at com.ethercamp.contrdata.storage.dictionary.Sha3Index.add(Sha3Index.java:85)
        at com.ethercamp.contrdata.storage.dictionary.StorageDictionaryVmHook.step(StorageDictionaryVmHook.java:69)
        at org.ethereum.vm.VM.lambda$step$0(VM.java:391)
        at org.ethereum.vm.VM.callVmHookAction(VM.java:1406)
        at org.ethereum.vm.VM.step(VM.java:391)
        at org.ethereum.vm.VM.play(VM.java:1366)
        at org.ethereum.core.TransactionExecutor.go(TransactionExecutor.java:312)
        at org.ethereum.core.PendingStateImpl.executeTx(PendingStateImpl.java:419)
        at org.ethereum.core.PendingStateImpl.addPendingTransactionImpl(PendingStateImpl.java:226)
        at org.ethereum.core.PendingStateImpl.addPendingTransactions(PendingStateImpl.java:166)
        at org.ethereum.net.eth.handler.Eth62.processTransactions(Eth62.java:406)
        at org.ethereum.net.eth.handler.Eth62.channelRead0(Eth62.java:153)
        at org.ethereum.net.eth.handler.Eth63.channelRead0(Eth63.java:83)
        at org.ethereum.net.eth.handler.Eth63.channelRead0(Eth63.java:56)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
        at org.ethereum.net.rlpx.NettyByteToMessageCodec.channelRead(NettyByteToMessageCodec.java:73)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at org.ethereum.net.server.WireTrafficStats$TrafficStatHandler.channelRead(WireTrafficStats.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by zilm13** [comment]
@MysticRyuujin yeah, it's an old bug, need to fix it too.
@eugene-shevchenko could you, please, take it? we have an issue for it: #73

**Comment by MysticRyuujin** [comment]
Alright! You can close this one then 😄

**Comment by zilm13** [comment]
@MysticRyuujin 👍
