### ISSUE TITLE
Missing file `org/ethereum/vm/VMHook.class`

### ISSUE THREAD

**Issue by MysticRyuujin** [ether-camp/ethereum-harmony#121]
Not sure why but when I try to start my node I'm getting this missing file error, not sure where that file comes from? I don't think it was deleted...:

```
08:15:55.555 INFO [general]  Config ( yes ): default properties from resource 'ethereumj.conf'
08:15:55.587 INFO [general]  Config ( yes ): user properties from -Dethereumj.conf.res resource(s) 'harmony.conf,ropsten.conf'
08:15:55.589 INFO [general]  Config ( yes ): user properties from resource 'user.conf'
08:15:55.589 INFO [general]  Config ( no  ): user properties from file '/root/ethereum-harmony/config/ethereumj.conf'
08:15:55.589 INFO [general]  Config ( no  ): test properties from resource 'test-ethereumj.conf'
08:15:55.590 INFO [general]  Config ( no  ): test properties from resource 'test-user.conf'
08:15:55.590 INFO [general]  Config ( no  ): user properties from -Dethereumj.conf.file file(s) 'null'
08:15:55.590 INFO [general]  Config ( no  ): config passed via constructor
     _____ _   _       _   _
    |  ___| | | |     | | | |
    | |__ | |_| |__   | |_| | __ _ _ __ _ __ ___   ___  _ __  _   _
    |  __|| __| '_ \  |  _  |/ _` | '__| '_ ` _ \ / _ \| '_ \| | | |
    | |___| |_| | | | | | | | (_| | |  | | | | | | (_) | | | | |_| |
    \____/ \__|_| |_| \_| |_/\__,_|_|  |_| |_| |_|\___/|_| |_|\__, |
                                                               __/ |
            By <Ether.Camp>                                   |___/

08:15:56.198 INFO [c.e.h.Application]  Starting Application on harmony01 with PID 29798 (/root/ethereum-harmony/build/classes/java/main started by root in /root/ethereum-harmony)
08:15:56.199 INFO [c.e.h.Application]  No active profile set, falling back to default profiles: default
08:15:56.776 ERROR [o.s.b.SpringApplication]  Application startup failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.ethercamp.harmony.Application]; nested exception is java.io.FileNotFoundException: class path resource [org/ethereum/vm/VMHook.class] cannot be opened 
because it does not exist
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:187)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:324)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:246)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:681)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
        at com.ethercamp.harmony.Application.main(Application.java:65)
Caused by: java.io.FileNotFoundException: class path resource [org/ethereum/vm/VMHook.class] cannot be opened because it does not exist
        at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:172)
        at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:50)
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:98)
        at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.createMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:89)
        at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.getMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:76)
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:93)
        at org.springframework.context.annotation.ConfigurationClassParser.asSourceClass(ConfigurationClassParser.java:640)
        at org.springframework.context.annotation.ConfigurationClassParser$SourceClass.getInterfaces(ConfigurationClassParser.java:816)
        at org.springframework.context.annotation.ConfigurationClassParser.processInterfaces(ConfigurationClassParser.java:350)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:307)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:237)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:196)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:279)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:237)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:196)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:279)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:237)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:204)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:173)
        ... 13 common frames omitted
:runRopsten FAILED
```

**Comment by zilm13** [comment]
@MysticRyuujin should be fixed with https://github.com/ether-camp/ethereum-harmony/commit/bc43df360a82eefe536d2ae20dd08ad6d2e58bc1
