### ISSUE TITLE
Build and publish self-contained executable Jar

### ISSUE THREAD

**Issue by Nashatyrev** [ether-camp/ethereum-harmony#15]
Harmony is intended to be a user friendly peer, so in my mind we need to allow user just download and run the Jar without building it from scratch (accounting the build is more complex than say EthJ core or Geth)

**Comment by cupuyc** [comment]
I wish peer could have ability to auto update. Either via updating codebase or via downloading new binaries.

**Comment by CovertEquation** [comment]
I've been trying to get the gradle shadowJar to run correctly, but keep getting: 
```org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:535)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
```
Additionally, when I try importing this into intelliJ, it freaks out about the lack of logger class. My gradle skills are a bit lacking but happy to help on getting this packaged.

**Comment by cupuyc** [comment]
@DaveWK I think I was able to build fat jar once with Spring Boot `bootRepackage` task:
https://docs.spring.io/spring-boot/docs/current/reference/html/build-tool-plugins-gradle-plugin.html#build-tool-plugins-gradle-repackage-configuration

I used that task while created desktop build in `desktop.gradle`
