### ISSUE TITLE
Building via Gradle Fails with ConfigException for ${database.name}

### ISSUE THREAD

**Issue by BHSDuncan** [ether-camp/ethereum-harmony#35]
I'm using the code from the latest pull from master (as of March 21, 2017).

The previous version I used (which was one prior to v2.1) did not suffer from this issue.

I'm running a private net, and have never specified any value for ${database.name} in either the runtime args or the private.conf file.  It would seem to me that now, for whatever reason, there is no default value for this property.

I'm sure I could work around it by changing the property to be a hardcoded value, but I still feel this should be addressed.

I'm running via ./gradlew bootRun -Dethereumj.conf.file=/path/to/private.conf -DgenesisFile=/path/to/genesis-private.conf -Dserver.port=8081

They're the exact same conf files that I've previously used successfully, and I do see that ${database.name} is left in the current master for src/main/resources/private.conf.

I didn't see any additional instructions on the README.md that indicate I should change or update anything related to this.  Still, I'm hoping I've just done something wrong.

Thanks in advance.

Stack trace is as follows:

```
12:16:56.886 ERROR [general]  Can't read config.
com.typesafe.config.ConfigException$UnresolvedSubstitution: /Users/duncan/code/ethereum-harmony-seed/src/main/resources/private.conf: 38: Could not resolve substitution to a value: ${database.name}
        at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:87)
        at com.typesafe.config.impl.ResolveSource.resolveCheckingReplacement(ResolveSource.java:110)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:114)
        at com.typesafe.config.impl.ConfigConcatenation.resolveSubstitutions(ConfigConcatenation.java:178)
        at com.typesafe.config.impl.ResolveSource.resolveCheckingReplacement(ResolveSource.java:110)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:114)
        at com.typesafe.config.impl.ConfigDelayedMerge.resolveSubstitutions(ConfigDelayedMerge.java:96)
        at com.typesafe.config.impl.ConfigDelayedMerge.resolveSubstitutions(ConfigDelayedMerge.java:59)
        at com.typesafe.config.impl.ResolveSource.resolveCheckingReplacement(ResolveSource.java:110)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:114)
        at com.typesafe.config.impl.SimpleConfigObject$1.modifyChildMayThrow(SimpleConfigObject.java:341)
        at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:280)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:321)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:25)
        at com.typesafe.config.impl.ResolveSource.resolveCheckingReplacement(ResolveSource.java:110)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:114)
        at com.typesafe.config.impl.SimpleConfigObject$1.modifyChildMayThrow(SimpleConfigObject.java:341)
        at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:280)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:321)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:25)
        at com.typesafe.config.impl.ResolveSource.resolveCheckingReplacement(ResolveSource.java:110)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:114)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:149)
        at com.typesafe.config.impl.SimpleConfig.resolveWith(SimpleConfig.java:70)
        at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:60)
        at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:55)
        at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:33)
        at org.ethereum.config.SystemProperties.<init>(SystemProperties.java:187)
        at org.ethereum.config.SystemProperties.<init>(SystemProperties.java:148)
        at org.ethereum.config.SystemProperties.<init>(SystemProperties.java:136)
        at org.ethereum.config.SystemProperties.getSpringDefault(SystemProperties.java:81)
        at org.ethereum.config.SystemProperties.getDefault(SystemProperties.java:76)
        at com.ethercamp.harmony.Application.main(Application.java:58)
Exception in thread "main" java.lang.RuntimeException: com.typesafe.config.ConfigException$UnresolvedSubstitution: /Users/duncan/code/ethereum-harmony-seed/src/main/resources/private.conf: 38: Could not resolve substitution to a value: ${database.name}
        at org.ethereum.config.SystemProperties.<init>(SystemProperties.java:204)
        at org.ethereum.config.SystemProperties.<init>(SystemProperties.java:148)
        at org.ethereum.config.SystemProperties.<init>(SystemProperties.java:136)
        at org.ethereum.config.SystemProperties.getSpringDefault(SystemProperties.java:81)
        at org.ethereum.config.SystemProperties.getDefault(SystemProperties.java:76)
        at com.ethercamp.harmony.Application.main(Application.java:58)
Caused by: com.typesafe.config.ConfigException$UnresolvedSubstitution: /Users/duncan/code/ethereum-harmony-seed/src/main/resources/private.conf: 38: Could not resolve substitution to a value: ${database.name}
        at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:87)
        at com.typesafe.config.impl.ResolveSource.resolveCheckingReplacement(ResolveSource.java:110)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:114)
        at com.typesafe.config.impl.ConfigConcatenation.resolveSubstitutions(ConfigConcatenation.java:178)
        at com.typesafe.config.impl.ResolveSource.resolveCheckingReplacement(ResolveSource.java:110)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:114)
        at com.typesafe.config.impl.ConfigDelayedMerge.resolveSubstitutions(ConfigDelayedMerge.java:96)
        at com.typesafe.config.impl.ConfigDelayedMerge.resolveSubstitutions(ConfigDelayedMerge.java:59)
        at com.typesafe.config.impl.ResolveSource.resolveCheckingReplacement(ResolveSource.java:110)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:114)
        at com.typesafe.config.impl.SimpleConfigObject$1.modifyChildMayThrow(SimpleConfigObject.java:341)
        at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:280)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:321)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:25)
        at com.typesafe.config.impl.ResolveSource.resolveCheckingReplacement(ResolveSource.java:110)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:114)
        at com.typesafe.config.impl.SimpleConfigObject$1.modifyChildMayThrow(SimpleConfigObject.java:341)
        at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:280)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:321)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:25)
        at com.typesafe.config.impl.ResolveSource.resolveCheckingReplacement(ResolveSource.java:110)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:114)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:149)
        at com.typesafe.config.impl.SimpleConfig.resolveWith(SimpleConfig.java:70)
        at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:60)
        at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:55)
        at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:33)
        at org.ethereum.config.SystemProperties.<init>(SystemProperties.java:187)
        ... 5 more
:bootRun FAILED
```

**Comment by cupuyc** [comment]
@BHSDuncan Thank you for filling issue.

Please don't use line from `private.conf` as a sample. It's wrong, but still workable as proper value is passed from gradle script. You can see that `./gradlew bootRun` works fine. 
Then please remove usage of `${database.name}` and set abs or relative path to your database (either in your `private.conf` or via `-D` prop).

This happened because fix for variable substitution is in ethereumJ-core `develop` branch, but Harmony was shipped with lower version of ethereumJ-core.

**Comment by cupuyc** [comment]
BTW here is sample of private network with Harmony and geth
https://github.com/ether-camp/harmony-examples

**Comment by BHSDuncan** [comment]
Good to know.  I know my/your workaround works, but, thanks for explaining why it happens.  As I'd said, my previous private network setup worked just fine.

Thank you for getting back to me so quickly. Love the product!
