### ISSUE TITLE
private network  mining Cause a mistake!!! Please help!!! thanks very much

### ISSUE THREAD

**Issue by qq940043871** [ether-camp/ethereum-harmony#60]
Caused by: java.lang.RuntimeException: Invalid Trie state, can't resolve hash 659a32f2610f4b8f76ed9f906d80b8a854573bd57a2dbe2b775ca4997257d7c3
	at org.ethereum.trie.TrieImpl$Node.resolve(TrieImpl.java:111)
	at org.ethereum.trie.TrieImpl$Node.parse(TrieImpl.java:204)
	at org.ethereum.trie.TrieImpl$Node.getType(TrieImpl.java:340)
	at org.ethereum.trie.TrieImpl.insert(TrieImpl.java:537)
	at org.ethereum.trie.TrieImpl.put(TrieImpl.java:531)
	at org.ethereum.trie.SecureTrie.put(SecureTrie.java:47)
	at org.ethereum.trie.SecureTrie.put(SecureTrie.java:26)
	at org.ethereum.datasource.SourceCodec.put(SourceCodec.java:48)
	at org.ethereum.datasource.WriteCache.flush(WriteCache.java:241)
	at org.ethereum.datasource.AbstractChainedSource.flush(AbstractChainedSource.java:66)
	at org.ethereum.datasource.SourceChainBox.flushImpl(SourceChainBox.java:77)
	at org.ethereum.datasource.AbstractChainedSource.flush(AbstractChainedSource.java:64)
	at org.ethereum.db.RepositoryRoot.getRoot(RepositoryRoot.java:120)
	at org.ethereum.core.BlockchainImpl.applyBlock(BlockchainImpl.java:912)
	at org.ethereum.core.BlockchainImpl.createNewBlock(BlockchainImpl.java:505)
	at org.ethereum.core.BlockchainImpl.createNewBlock(BlockchainImpl.java:471)
	at org.ethereum.mine.BlockMiner.getNewBlockForMining(BlockMiner.java:249)
	at org.ethereum.mine.BlockMiner.restartMining(BlockMiner.java:255)
	at org.ethereum.mine.BlockMiner.startMining(BlockMiner.java:141)
	at org.ethereum.mine.BlockMiner.<init>(BlockMiner.java:116)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	... 67 common frames omitted

**Comment by mkalinin** [comment]
what version do you use? try to set `database.prune.enabled = false` in config and start from scratch

**Comment by mkalinin** [comment]
what version do you use? try to set `database.prune.enabled = false` in config and start from scratch

**Comment by qq940043871** [comment]
harmony app.version = v.2.1

**Comment by qq940043871** [comment]
genesis-private.json
{
"nonce": "0x0000000000000088",
"difficulty": "0x0200",
"mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
"coinbase": "0x0000000000000000000000000000000000000000",
"timestamp": "0x00",
"parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"extraData": "0x",
"gasLimit": "0x13880000000000",
"alloc": {
"0000000000000000000000000000000000000001": { "balance": "1" },
"0000000000000000000000000000000000000002": { "balance": "1" },
"0000000000000000000000000000000000000003": { "balance": "1" },
"0000000000000000000000000000000000000004": { "balance": "1" },
"102e61f5d8f9bc71d0ad4a084df4e65e05ce0e1c": { "balance": "1606938044258990275541962092341162602522202993782792835301376" },
"cd2a3d9f938e13cd947ec05abc7fe734df8dd826": { "balance": "10000000000000000" }
},
"config": {
"homesteadBlock": 20,
"daoForkBlock": 20,
"daoForkSupport": false,
"eip150Block": 20,
"eip158Block": 20,
"eip155Block": 20
}
}

**Comment by qq940043871** [comment]
when my genesis-private.json change
{
"nonce": "0x0000000000000088",
"difficulty": "0x0200",
"mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
"coinbase": "0x0000000000000000000000000000000000000000",
"timestamp": "0x00",
"parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"extraData": "0x",
"gasLimit": "0x13880000000000",
"alloc": {
},
"config": {
"homesteadBlock": 20,
"daoForkBlock": 20,
"daoForkSupport": false,
"eip150Block": 20,
"eip158Block": 20,
"eip155Block": 20
}
}
the problem is missing!
but when miner_start block mined ,my coinbase address balance is always 0

**Comment by qq940043871** [comment]
node> eth_getBlockByNumber 8000 true
{
"number": "0x1f40",
"hash": "0x955f23cf21eef6f7158522172d273f5368dd0068324b01ec266ebac301fe5cd1",
"parentHash": "0x9148f59b3798420e47419be16df379df912ce4c9e2ac314827931a73e31e7823",
"nonce": "0x797bce3ae0825f31",
"sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
"logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000",
"transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
"stateRoot": "0xf519f92b8d4a1a79b991660baf71abfcc2b1933e0716a1cb0a513ac230f9cce6",
"receiptRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
"miner": "0x782446629a16c729248eef9e466a35b5fbe5fee4",
"difficulty": "0x200",
"totalDifficulty": "0x3e8200",
"extraData": "0x457468657265756d4a20706f7765726564",
"size": "0x215",
"gasLimit": "0x13880000000000",
"gasUsed": "0x0",
"timestamp": "0x5a990b14",
"transactions": [],
"uncles": []
}
node> eth_getBalance 0x782446629a16c729248eef9e466a35b5fbe5fee4 111111
JsonRpcServerError: null
node> eth_getBalance 0x782446629a16c729248eef9e466a35b5fbe5fee4 11111
"0x0"

**Comment by mkalinin** [comment]
how do you run Harmony?

**Comment by qq940043871** [comment]
eclipse application run

**Comment by mkalinin** [comment]
try to execute gradle task `runPrivate` in Eclipse?

**Comment by qq940043871** [comment]
Version: Neon Release (4.6.0) 
one problem:
if my JDK Inconsistent with operating system time zone. I don't know if it can

**Comment by qq940043871** [comment]
when gradle success  , imoport eclipse

**Comment by mkalinin** [comment]
`runPrivate` task runs Harmony with predefined `private.conf` which is configured as a private miner. If you want to setup a custom private network this guide can help you to do this https://github.com/ether-camp/ethereum-harmony/wiki/Setting-up-a-private-network

**Comment by qq940043871** [comment]
OK.  I will try! thank you!

**Comment by qq940043871** [comment]
because i don't understand gradle ,case the problem ,when I gradle runPrivate, it work well.,now it work well
thank you
