### ISSUE TITLE
Uncritical errors while running Harmony

### ISSUE THREAD

**Issue by zilm13** [ether-camp/ethereum-harmony#73]
Repeated exceptions like this:
```
ERROR [c.e.c.s.d.StorageDictionaryVmHook]  Error within handler: 
java.util.ConcurrentModificationException: null
	at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1643)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at com.ethercamp.contrdata.storage.dictionary.Sha3Index.contains(Sha3Index.java:79)
	at com.ethercamp.contrdata.storage.dictionary.Sha3Index.add(Sha3Index.java:85)
	at com.ethercamp.contrdata.storage.dictionary.StorageDictionaryVmHook.step(StorageDictionaryVmHook.java:69)
	at org.ethereum.vm.VM.step(VM.java:369)
	at org.ethereum.vm.VM.play(VM.java:1316)
	at org.ethereum.vm.program.Program.callToAddress(Program.java:606)
	at org.ethereum.vm.VM.step(VM.java:1243)
	at org.ethereum.vm.VM.play(VM.java:1316)
	at org.ethereum.core.TransactionExecutor.go(TransactionExecutor.java:313)
	at org.ethereum.core.BlockchainImpl.applyBlock(BlockchainImpl.java:876)
	at org.ethereum.core.BlockchainImpl.processBlock(BlockchainImpl.java:846)
	at org.ethereum.core.BlockchainImpl.addImpl(BlockchainImpl.java:577)
	at org.ethereum.core.BlockchainImpl.add(BlockchainImpl.java:527)
	at org.ethereum.core.BlockchainImpl.tryToConnect(BlockchainImpl.java:434)
	at org.ethereum.sync.SyncManager.produceQueue(SyncManager.java:263)
	at java.lang.Thread.run(Thread.java:745)

ERROR [c.e.c.s.d.StorageDictionaryVmHook]  Error within handler: 
java.util.ConcurrentModificationException: null
	at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1643)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at com.ethercamp.contrdata.storage.dictionary.Sha3Index.contains(Sha3Index.java:79)
	at com.ethercamp.contrdata.storage.dictionary.Sha3Index.add(Sha3Index.java:85)
	at com.ethercamp.contrdata.storage.dictionary.StorageDictionaryVmHook.step(StorageDictionaryVmHook.java:69)
	at org.ethereum.vm.VM.step(VM.java:369)
	at org.ethereum.vm.VM.play(VM.java:1316)
	at org.ethereum.core.TransactionExecutor.go(TransactionExecutor.java:313)
	at org.ethereum.core.PendingStateImpl.executeTx(PendingStateImpl.java:418)
	at org.ethereum.core.PendingStateImpl.updateState(PendingStateImpl.java:397)
	at org.ethereum.core.PendingStateImpl.processBest(PendingStateImpl.java:322)
	at org.ethereum.core.BlockchainImpl.lambda$tryToConnect$0(BlockchainImpl.java:459)
	at org.ethereum.core.EventDispatchThread.lambda$invokeLater$1(EventDispatchThread.java:78)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

ERROR [c.e.c.s.d.StorageDictionaryVmHook]  Error within handler: 
java.util.ConcurrentModificationException: null
	at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1643)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at com.ethercamp.contrdata.storage.dictionary.Sha3Index.contains(Sha3Index.java:79)
	at com.ethercamp.contrdata.storage.dictionary.Sha3Index.add(Sha3Index.java:85)
	at com.ethercamp.contrdata.storage.dictionary.StorageDictionaryVmHook.step(StorageDictionaryVmHook.java:69)
	at org.ethereum.vm.VM.step(VM.java:369)
	at org.ethereum.vm.VM.play(VM.java:1316)
	at org.ethereum.core.TransactionExecutor.go(TransactionExecutor.java:313)
	at org.ethereum.core.BlockchainImpl.applyBlock(BlockchainImpl.java:876)
	at org.ethereum.core.BlockchainImpl.processBlock(BlockchainImpl.java:846)
	at org.ethereum.core.BlockchainImpl.addImpl(BlockchainImpl.java:577)
	at org.ethereum.core.BlockchainImpl.add(BlockchainImpl.java:527)
	at org.ethereum.core.BlockchainImpl.tryConnectAndFork(BlockchainImpl.java:373)
	at org.ethereum.core.BlockchainImpl.tryToConnect(BlockchainImpl.java:443)
	at org.ethereum.sync.SyncManager.produceQueue(SyncManager.java:263)
	at java.lang.Thread.run(Thread.java:745)

ERROR [c.e.c.s.d.StorageDictionaryVmHook]  Error within handler: 
java.util.ConcurrentModificationException: null
	at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1643)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at com.ethercamp.contrdata.storage.dictionary.Sha3Index.contains(Sha3Index.java:79)
	at com.ethercamp.contrdata.storage.dictionary.Sha3Index.add(Sha3Index.java:85)
	at com.ethercamp.contrdata.storage.dictionary.StorageDictionaryVmHook.step(StorageDictionaryVmHook.java:69)
	at org.ethereum.vm.VM.step(VM.java:369)
	at org.ethereum.vm.VM.play(VM.java:1316)
	at org.ethereum.vm.program.Program.callToAddress(Program.java:606)
	at org.ethereum.vm.VM.step(VM.java:1243)
	at org.ethereum.vm.VM.play(VM.java:1316)
	at org.ethereum.core.TransactionExecutor.go(TransactionExecutor.java:313)
	at org.ethereum.core.PendingStateImpl.executeTx(PendingStateImpl.java:418)
	at org.ethereum.core.PendingStateImpl.updateState(PendingStateImpl.java:397)
	at org.ethereum.core.PendingStateImpl.processBest(PendingStateImpl.java:322)
	at org.ethereum.core.BlockchainImpl.lambda$tryToConnect$0(BlockchainImpl.java:459)
	at org.ethereum.core.EventDispatchThread.lambda$invokeLater$1(EventDispatchThread.java:78)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

ERROR [c.e.c.s.d.StorageDictionaryVmHook]  Error within handler: 
java.util.ConcurrentModificationException: null
	at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1643)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at com.ethercamp.contrdata.storage.dictionary.Sha3Index.contains(Sha3Index.java:79)
	at com.ethercamp.contrdata.storage.dictionary.Sha3Index.add(Sha3Index.java:85)
	at com.ethercamp.contrdata.storage.dictionary.StorageDictionaryVmHook.step(StorageDictionaryVmHook.java:69)
	at org.ethereum.vm.VM.step(VM.java:369)
	at org.ethereum.vm.VM.play(VM.java:1316)
	at org.ethereum.vm.program.Program.callToAddress(Program.java:606)
	at org.ethereum.vm.VM.step(VM.java:1243)
	at org.ethereum.vm.VM.play(VM.java:1316)
	at org.ethereum.core.TransactionExecutor.go(TransactionExecutor.java:313)
	at org.ethereum.core.BlockchainImpl.applyBlock(BlockchainImpl.java:876)
	at org.ethereum.core.BlockchainImpl.processBlock(BlockchainImpl.java:846)
	at org.ethereum.core.BlockchainImpl.addImpl(BlockchainImpl.java:577)
	at org.ethereum.core.BlockchainImpl.add(BlockchainImpl.java:527)
	at org.ethereum.core.BlockchainImpl.tryConnectAndFork(BlockchainImpl.java:373)
	at org.ethereum.core.BlockchainImpl.tryToConnect(BlockchainImpl.java:443)
	at org.ethereum.sync.SyncManager.produceQueue(SyncManager.java:263)
	at java.lang.Thread.run(Thread.java:745)			

ERROR [c.e.c.s.d.StorageDictionaryVmHook]  Error within handler: 
java.util.ConcurrentModificationException: null
	at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1643)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at com.ethercamp.contrdata.storage.dictionary.Sha3Index.contains(Sha3Index.java:79)
	at com.ethercamp.contrdata.storage.dictionary.Sha3Index.add(Sha3Index.java:85)
	at com.ethercamp.contrdata.storage.dictionary.StorageDictionaryVmHook.step(StorageDictionaryVmHook.java:69)
	at org.ethereum.vm.VM.step(VM.java:369)
	at org.ethereum.vm.VM.play(VM.java:1316)
	at org.ethereum.core.TransactionExecutor.go(TransactionExecutor.java:313)
	at org.ethereum.core.BlockchainImpl.applyBlock(BlockchainImpl.java:876)
	at org.ethereum.core.BlockchainImpl.processBlock(BlockchainImpl.java:846)
	at org.ethereum.core.BlockchainImpl.addImpl(BlockchainImpl.java:577)
	at org.ethereum.core.BlockchainImpl.add(BlockchainImpl.java:527)
	at org.ethereum.core.BlockchainImpl.tryToConnect(BlockchainImpl.java:434)
	at org.ethereum.sync.SyncManager.produceQueue(SyncManager.java:263)
	at java.lang.Thread.run(Thread.java:745)

ERROR [c.e.c.s.d.StorageDictionaryVmHook]  Error within handler: 
java.util.ConcurrentModificationException: null
	at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1643)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at com.ethercamp.contrdata.storage.dictionary.Sha3Index.contains(Sha3Index.java:79)
	at com.ethercamp.contrdata.storage.dictionary.Sha3Index.add(Sha3Index.java:85)
	at com.ethercamp.contrdata.storage.dictionary.StorageDictionaryVmHook.step(StorageDictionaryVmHook.java:69)
	at org.ethereum.vm.VM.step(VM.java:369)
	at org.ethereum.vm.VM.play(VM.java:1316)
	at org.ethereum.core.TransactionExecutor.go(TransactionExecutor.java:313)
	at org.ethereum.core.PendingStateImpl.executeTx(PendingStateImpl.java:418)
	at org.ethereum.core.PendingStateImpl.addPendingTransactionImpl(PendingStateImpl.java:225)
	at org.ethereum.core.PendingStateImpl.addPendingTransactions(PendingStateImpl.java:165)
	at org.ethereum.net.eth.handler.Eth62.processTransactions(Eth62.java:405)
	at org.ethereum.net.eth.handler.Eth62.channelRead0(Eth62.java:152)
	at org.ethereum.net.eth.handler.Eth63.channelRead0(Eth63.java:82)
	at org.ethereum.net.eth.handler.Eth63.channelRead0(Eth63.java:55)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at org.ethereum.net.rlpx.NettyByteToMessageCodec.channelRead(NettyByteToMessageCodec.java:73)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at org.ethereum.net.server.WireTrafficStats$TrafficStatHandler.channelRead(WireTrafficStats.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
	at java.lang.Thread.run(Thread.java:745)	
```

**Comment by zilm13** [comment]
Looking at the decompiled sources, this map in `com.ethercamp.contrdata.storage.dictionary.Sha3Index` is modified concurrently by blocks import and pending state simultaneously:
```
    private final Map<Sha3Index.Sha3Output, Sha3Index.Entry> idx = new HashMap();
```
Exception is catched within `com.ethercamp.contrdata.storage.dictionary.StorageDictionaryVmHook` and not thrown to the upper levels, so it doesn't affect anything except contract storage consistency.

There are too possible solutions for the issue:
1) Fix the bug - not available currently
2) Remove such kind of logs from logging - not recommended, because in case of contract storage of inconsistency there should be answer, what was the reason

@mkalinin what do you think?

**Comment by mkalinin** [comment]
Let's get back to it after solving https://github.com/ethereum/ethereumj/issues/1070

**Comment by MysticRyuujin** [comment]
Hello, I just wanted to say that this issue is no longer trivial for me...

These errors are piling up so fast that my debug log is taking up almost 140GB...

```
root@harmony01:~/.gradle/daemon/4.6# pwd
/root/.gradle/daemon/4.6
root@harmony01:~/.gradle/daemon/4.6# du -sch .[!.]* * | sort -h
du: cannot access '.[!.]*': No such file or directory
4.0K    daemon-25278.out.log
4.0K    registry.bin
4.0K    registry.bin.lock
20K     daemon-59232.out.log
20K     daemon-696.out.log
28K     daemon-1383.out.log
28K     daemon-73013.out.log
28K     daemon-885.out.log
56K     daemon-763.out.log
60K     daemon-729.out.log
68K     daemon-744.out.log
92K     daemon-42884.out.log
152K    daemon-742.out.log
200K    daemon-38554.out.log
244K    daemon-707.out.log
340K    daemon-651.out.log
496K    daemon-733.out.log
1.5M    daemon-695.out.log
2.0M    daemon-705.out.log
2.3M    daemon-703.out.log
2.3M    daemon-736.out.log
3.1M    daemon-39490.out.log
3.1M    daemon-761.out.log
3.3M    daemon-730.out.log
3.8M    daemon-701.out.log
5.0M    daemon-740.out.log
7.8M    daemon-789.out.log
9.1M    daemon-741.out.log
17M     daemon-766.out.log
18M     daemon-1436.out.log
20M     daemon-712.out.log
22M     daemon-693.out.log
29M     daemon-11816.out.log
35M     daemon-668.out.log
39M     daemon-727.out.log
81M     daemon-702.out.log
95M     daemon-743.out.log
96M     daemon-23307.out.log
111M    daemon-760.out.log
203M    daemon-720.out.log
845M    daemon-799.out.log
1.5G    daemon-694.out.log
2.8G    daemon-722.out.log
16G     daemon-784.out.log
122G    daemon-782.out.log
143G    total
```

I suppose I could turn off debug logging of these particular errors, somehow, though I don't know how...

**Comment by zilm13** [comment]
@MysticRyuujin we'll fix it soon, it requires some changes to EthereumJ too.
Me or @eugene-shevchenko will ping you back when the fix is done.

**Comment by flian** [comment]
Hello, I found it may cause OOM for main net.
after this error happen, seems 'EventDispatchThread.executorQueue' will continue increase until OOM.

I just print queue size for debug, major logs like :
"executorQueue  size: 32"
"executorQueue size: 6457999"
"executorQueue size: 17924963"
...

follow are heap snapshot after OOM:
![oom](https://user-images.githubusercontent.com/6668497/45604597-79585f80-ba68-11e8-9c06-41702d9aa37a.png)

following are more detail:
start scripts:
` java -server -Xss2M -XX:+PrintGCTimeStamps -XX:+PrintGCDetails -Xloggc:./logs/main_gc.log -Xms4G -Xmx4G -Dethereumj.conf.res=ethereumj.conf -DnetworkProfile=main -Ddatabase.dir=database/database -Dmine.cpuMineThreads=1 -Dmine.fullDataSet=false  -Dsync.fast.enabled=true -Dsync.fast.skipHistory=false   -jar at2plus-ethereum-gateway.jar & `
