### ISSUE TITLE
Stopped Syncing #5,503,550

### ISSUE THREAD

**Issue by MysticRyuujin** [ether-camp/ethereum-harmony#80]
My node has stopped syning for almost 10 days now, and I've tried clearing caches, restarting, updating, etc.

I stopped the process, cleared the logs, cleared the cache, pulled the latest from git, started it, let it run a little while, collected the logs. Here they are:

[harmonylogs.zip](https://github.com/ether-camp/ethereum-harmony/files/1976751/harmonylogs.zip)

The only error I see is here:

```
07:24:43.220 DEBUG [net]  From: 3ac0505a | /34.228.13.147:30303    Recv:  [TRANSACTIONS num:1 
   TransactionData [hash=51289f1df5c13ef949c8e4521e4176d22669518f17239366f0813cffdbb984f3  nonce=13, gasPrice=3b9aca00, gas=8fc8, receiveAddress=c20464e0c373486d2b3335576e83a218b1618a5e, sendAddress=aff6d189f1f7090695cd3a5aabb5c9bf168e22a3, value=, data=a9
059cbb0000000000000000000000009c0c31426f81968e9e6efd9740a7df8a89d6d839000000000000000000000000000000000000000000000000a688906bd8b00000, signatureV=28, signatureR=9f6a5451217379d6f8293f9a246421c893f20659b1bb627bc31830bb13e5e115, signatureS=172fadbd2471921ea
535f241b641615a78f6bed77af8690e4e802c2b5baaddc1]]
07:24:43.210 ERROR [blockchain]  Unexpected error: 
java.lang.NullPointerException: null
        at org.ethereum.db.prune.ChainItem.<init>(ChainItem.java:20)
        at org.ethereum.db.prune.Segment.<init>(Segment.java:41)
        at org.ethereum.db.PruneManager.blockCommitted(PruneManager.java:94)
        at org.ethereum.core.BlockchainImpl.storeBlock(BlockchainImpl.java:983)
        at org.ethereum.core.BlockchainImpl.lambda$addImpl$1(BlockchainImpl.java:629)
        at org.ethereum.db.DbFlushManager.commit(DbFlushManager.java:108)
        at org.ethereum.core.BlockchainImpl.addImpl(BlockchainImpl.java:628)
        at org.ethereum.core.BlockchainImpl.add(BlockchainImpl.java:529)
        at org.ethereum.core.BlockchainImpl.tryConnectAndFork(BlockchainImpl.java:375)
        at org.ethereum.core.BlockchainImpl.tryToConnect(BlockchainImpl.java:445)
        at org.ethereum.sync.SyncManager.produceQueue(SyncManager.java:263)
        at java.lang.Thread.run(Thread.java:748)
07:24:43.221 INFO [sync]  Sync state: Regular (0 of 0), last block #5507018, best known #5560925; Import idle time 1m7s of total 5m
```

**Comment by mkalinin** [comment]
to get a full understanding of what has happened I am wonder whether you did change `database.prune.maxDepth` in the config or not?

**Comment by mkalinin** [comment]
@MysticRyuujin would it be a problem for you to upload `database` folder to some resource? I made a fix and would like to test it with your data sample

**Comment by mkalinin** [comment]
This should be fixed by https://github.com/ethereum/ethereumj/commit/99e22a557a7f88cc308f7931548cefefcaabb9cc
@MysticRyuujin thanks a lot for assistance!
